[build]
  command = "pip install -r functions/main/requirements.txt && mkdir -p public && cp -r static/* public/"
  publish = "public"
  functions = "functions"

[[redirects]]
from = "/*"
to = "/.functions/main"
status = 200

[dev]
framework = "#static"
targetPort = 8000
